---
title: "day4-comp2"
format: html
editor: visual
execute: 
  warning: FALSE
---

```{r}
library(GGally)
library(skimr)
library(palmerpenguins)
library(tidyverse)
```

# Basic data exploration

```{r}
view(penguins)
```

-   names: get variable names

-   dim: get data dimensions

-   head: get first n lines (6 by default)

-   tail: get last n lines (6 by default)

-   summary: get basic summary statistics

```{r}
names(penguins)
dim(penguins)
head(penguins)
tail(penguins)
summary(penguins)
```

```{r}
skimr::skim(penguins)
```

```{r}
ggpairs(penguins)
# show a whole grid / relationship with variables / 
```

## Making more exploratory charts in ggplot2

Histogram

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm)) + 
  geom_histogram(aes(fill=species)) + 
  theme_minimal()
#aes 
```

```{r}
ggplot(data = penguins, aes(x=species, y = bill_length_mm)) + 
  geom_boxplot(fill = "yellow",aes (color = island)) +
  geom_jitter(alpha = 0.5, aes(size= bill_length_mm, color = bill_depth_mm)) + 
  theme_dark()

```
